version: '3'
services:
  nacos:
    image: zhusaidong/nacos-server-m1:2.0.3
    container_name: nacos
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 127.0.0.1
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#      NACOS_AUTH_IDENTITY_KEY: 2222
#      NACOS_AUTH_IDENTITY_VALUE: 2xxx
#      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
