server:
  port: 7002

spring:
  application:
    name: @artifactId@

raincloud:
  openapi:
    url: http://localhost:7002
    version: 1.0

springdoc:
#  packages-to-scan:
#  paths-to-match:

  api-docs:
    enabled: true # default; 开关 json 格式 api 文档, 必须开启, 否则 swagger ui 无法渲染
    path: /v3/api-docs # default; 控制 json 格式 api 文档路径, so we can check http://localhost:7002/v3/api-docs
#    resolve-schema-properties: true # default to false

  swagger-ui:
    enabled: true # default;
    disable-swagger-default-url: true # default to false; don't allow show example apis
    path: /swagger-ui.html # default; 会重定向到 index.html
    use-root-path: false # default to false; 是否使用根路径作为 "/swagger-ui"
    csrf:
      enabled: true # default to false;
    url: ${springdoc.api-docs.path} # seems invalid
#    query-config-enabled: true # default to false; 从 浏览器 URL 种读取参数configUrl
#    config-url: ${springdoc.api-docs.path} # load external api-docs
  #    urls-primary-name: myGroup

  show-actuator: true # default to false; 开启显示 actuator apis
  show-login-endpoint: true # default to false; make spring security login-endpoint visible



